# Generated by Django 5.2.7 on 2026-01-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='weather.weathersearch')),
            ],
        ),
    ]
